// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy58yqdzMokNKT-Z4qCzisypFuJijP118',
    appId: '1:355998195019:web:90799f0d7534972c641cce',
    messagingSenderId: '355998195019',
    projectId: 'dolce-italia-3606f',
    authDomain: 'dolce-italia-3606f.firebaseapp.com',
    storageBucket: 'dolce-italia-3606f.appspot.com',
    measurementId: 'G-18YYC5DJ4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHrO0HHWk1GZUIEkzLc_opa1FcFZ_yXUM',
    appId: '1:355998195019:android:7483792a28d256f4641cce',
    messagingSenderId: '355998195019',
    projectId: 'dolce-italia-3606f',
    storageBucket: 'dolce-italia-3606f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKz6lBhZ8YrpNn65R75std0nAnrf8g7ac',
    appId: '1:355998195019:ios:efe0a63e10fcb16c641cce',
    messagingSenderId: '355998195019',
    projectId: 'dolce-italia-3606f',
    storageBucket: 'dolce-italia-3606f.appspot.com',
    iosBundleId: 'com.example.primeStream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKz6lBhZ8YrpNn65R75std0nAnrf8g7ac',
    appId: '1:355998195019:ios:efe0a63e10fcb16c641cce',
    messagingSenderId: '355998195019',
    projectId: 'dolce-italia-3606f',
    storageBucket: 'dolce-italia-3606f.appspot.com',
    iosBundleId: 'com.example.primeStream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy58yqdzMokNKT-Z4qCzisypFuJijP118',
    appId: '1:355998195019:web:4a288da3d04a792e641cce',
    messagingSenderId: '355998195019',
    projectId: 'dolce-italia-3606f',
    authDomain: 'dolce-italia-3606f.firebaseapp.com',
    storageBucket: 'dolce-italia-3606f.appspot.com',
    measurementId: 'G-0R3BJQT00K',
  );
}
